name: Create initialization issue on repository dispatch
on:
  push:
    branches: main

jobs:
  create_issue:
    runs-on: ubuntu-latest
    if: ${{ github.repository != 'cioos-siooc/cioos-catalogue-map-template' }}
    steps:
      - uses: actions/checkout@v4
      - name: Update README and issue template
        run: |
          sed -i 's|# cioos-catalogue-map-template|# ${{ github.repository }}|g' README.md
          OWNER=${GITHUB_REPOSITORY_OWNER}
          REPO=${GITHUB_REPOSITORY#*/}
          PAGES_URL="https://${OWNER}.github.io/${REPO}"
          sed -i "s|https://cioos-siooc.github.io/cioos-catalogue-map-template|${PAGES_URL}|g" README.md
          sed -i "s|https://cioos-siooc.github.io/cioos-catalogue-map-template|${PAGES_URL}|g" .github/ISSUE_TEMPLATE/init-catalogue-map.md
      - name: Create issue
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs')
            // Read the issue body from a file
            const issueBody = fs.readFileSync('.github/ISSUE_TEMPLATE/init-catalogue-map.md', 'utf8')

            // Create the issue
            const issue = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Initialize Catalogue Map',
              body: issueBody,
            }
            github.rest.issues.create(issue)
      - name: Cleanup repository initialization files
        run: |
          rm -rf .github/workflows/init-catalogue-map.yaml
          rm -rf .github/ISSUE_TEMPLATE/init-catalogue-map.md
      - name: Change CODEOWNER to github actor
        run: |
          echo "* @$GITHUB_ACTOR" > CODEOWNERS
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
